services:
  - type: web
    name: mypocket-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DB_DIR
        value: /var/data
    disk:
      name: mypocket-db
      mountPath: /var/data
      sizeGB: 1
